org: georgedavis
app: filestoragesecurity-malwaretest
service: filestoragesecurity-malwaretest

frameworkVersion: '2 || 3'

custom:
  defaultStage: dev
  stages:
    dev:
      profile: default
      region: us-east-2
      buckets: filestoragesecurity-ingestbucket,filestoragesecurity-ingestbucket-2,filestoragesecurity-ingestbucket-3-ca
      hours: 3
    prod:
      profile: serverless
      region: us-east-1
      buckets: serverless-cloudone
      hours: 1

provider:
  name: aws
  runtime: python3.8
  profile: ${self:custom.stages.${opt:stage}.profile}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.stages.${opt:stage}.region}
  memorySize: 512
  timeout: 300
  logRetentionInDays: 14
  environment:
    awsRegion: ${self:custom.stages.${opt:stage}.region}
    s3IngestBucketName: ${self:custom.stages.${opt:stage}.buckets}
    timeDeltaInLogQuery: 6 # In hours
  tags:
    BusinessCase: FSS-MalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  stackTags:
    BusinessCase: FSS-MalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  iam:
    role:
      name: filestoragesecurity-malwaretest-${opt:stage, self:custom.defaultStage}
      path: /
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 
            - 's3:*'
            - 'kms:*'
            - 'logs:*'
      tags:
        BusinessCase: FSS-MalwareTest
        Owner: TrendMicro
        CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: handler.main
    description: Scheduled run of File Storage Security Malware Test Tasks    
    events:
      - schedule:
          name: scheduled-filestoragesecurity-malwaretest-${opt:stage, self:custom.defaultStage}
          description: 'Cloud One File Storage Security Hourly Malware Test Schedule'
          rate: cron(0 ${self:custom.stages.${opt:stage}.hours} * * ? *)

plugins:
  - serverless-python-requirements
  
package:
  individually: true
  excludeDevDependencies: false
  include:
    - "!node_modules/**"