org: georgedavis
app: filestoragesecurity-malwaretest
service: filestoragesecurity-malwaretest

frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: python3.8
  stage: prod
  region: us-east-2
  memorySize: 512
  timeout: 180
  logRetentionInDays: 14
  environment:
    awsRegion: us-east-2
    s3IngestBucketName: filestoragesecurity-ingestbucket
    timeDeltaInLogQuery: 6 # In hours
  tags:
    BusinessCase: FSS-MalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  stackTags:
    BusinessCase: FSS-MalwareTest
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  iam:
    role:
      name: filestoragesecurity-malwaretest
      path: /
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 
            - 's3:*'
            - 'kms:*'
            - 'logs:*'
      tags:
        BusinessCase: FSS-MalwareTest
        Owner: TrendMicro
        CodeSource: https://github.com/GeorgeDavis-TM/filestoragesecurity-malwaretest.git
  lambdaHashingVersion: 20201221

functions:
  main:
    handler: handler.main
    description: Scheduled run of File Storage Security Malware Test Tasks    
    events:
      - schedule:
          name: scheduled-filestoragesecurity-malwaretest
          description: 'Cloud One File Storage Security Hourly Malware Test Schedule'
          rate: rate(1 hour)

plugins:
  - serverless-python-requirements

package:
  individually: true
  excludeDevDependencies: false
  include:
   - "!node_modules/**"